version: '3.1'
services:
  phx:
    image: resuelve/phoenix:elixir-1.6.6
    ports:
      - "${PHX_HOST_PORT:-4000}:${PHX_PORT:-4000}"
    volumes:
      - ./src:/app/src
      - ./src/_build/prod/rel:/app/src/_build/prod/rel
      - phx.deps:/app/src/deps
      - phx.builds:/app/src/_build
    environment:
      - MIX_ENV=${ENV:-dev}
      - PHX_PORT=${PHX_PORT:-4000}
      - PHX_URL=${PHX_HOST:-localhost}
      - PHX_SECRET_KEY_BASE=${PHX_SECRET_KEY_BASE}
      - PG_KOLOMBIA_URL=ecto://postgres:postgres@postgres/kolombia_${ENV:-dev}
      - SENDGRID_APIKEY=${SENDGRID_APIKEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}

    working_dir: /app/src
    command: mix phx.server

volumes:
  phx.deps:
  phx.builds:
